export const LOAD_LOGIN = "LOAD_LOGIN";
export const LOAD_LOGIN_PENDING = "LOAD_LOGIN_PENDING";
export const LOAD_LOGIN_FULFILLED = "LOAD_LOGIN_FULFILLED";
export const LOAD_LOGIN_REJECTED = "LOAD_LOGIN_REJECTED";

export const SIGNUP = "SIGNUP";
export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_FULFILLED = "SIGNUP_FULFILLED";
export const SIGNUP_REJECTED = "SIGNUP_REJECTED";

export const CHANGE_STATUS = "CHANGE_STATUS";
