export const LOAD_LOGIN = "LOAD_LOGIN";
export const LOAD_LOGIN_PENDING = "LOAD_LOGIN_PENDING";
export const LOAD_LOGIN_FULFILLED = "LOAD_LOGIN_FULFILLED";
export const LOAD_LOGIN_REJECTED = "LOAD_LOGIN_REJECTED";

export const SIGNUP = "SIGNUP";
export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_FULFILLED = "SIGNUP_FULFILLED";
export const SIGNUP_REJECTED = "SIGNUP_REJECTED";

export const POST_ARTICLE = "POST_ARTICLE";
export const POST_ARTICLE_PENDING = "POST_ARTICLE_PENDING";
export const POST_ARTICLE_FULFILLED = "POST_ARTICLE_FULFILLED";
export const POST_ARTICLE_REJECTED = "POST_ARTICLE_REJECTED";

export const FETCH_ALL_ARTICLE = "FETCH_ALL_ARTICLE";
export const FETCH_ALL_ARTICLE_PENDING = "FETCH_ALL_ARTICLE_PENDING";
export const FETCH_ALL_ARTICLE_FULFILLED = "FETCH_ALL_ARTICLE_FULFILLED";
export const FETCH_ALL_ARTICLE_REJECTED = "FETCH_ALL_ARTICLE_REJECTED";

export const ADD_RECEIVED_ARTICLE = "ADD_RECEIVED_ARTICLE";

export const CHANGE_STATUS = "CHANGE_STATUS";
