export const LOAD_LOGIN = "LOAD_LOGIN";
export const LOAD_LOGIN_PENDING = "LOAD_LOGIN_PENDING";
export const LOAD_LOGIN_FULFILLED = "LOAD_LOGIN_FULFILLED";
export const LOAD_LOGIN_REJECTED = "LOAD_LOGIN_REJECTED";
